// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-consumer/consumers (interfaces: IConsumer)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIConsumer is a mock of IConsumer interface.
type MockIConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockIConsumerMockRecorder
}

// MockIConsumerMockRecorder is the mock recorder for MockIConsumer.
type MockIConsumerMockRecorder struct {
	mock *MockIConsumer
}

// NewMockIConsumer creates a new mock instance.
func NewMockIConsumer(ctrl *gomock.Controller) *MockIConsumer {
	mock := &MockIConsumer{ctrl: ctrl}
	mock.recorder = &MockIConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConsumer) EXPECT() *MockIConsumerMockRecorder {
	return m.recorder
}

// StartConsumer mocks base method.
func (m *MockIConsumer) StartConsumer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartConsumer")
}

// StartConsumer indicates an expected call of StartConsumer.
func (mr *MockIConsumerMockRecorder) StartConsumer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartConsumer", reflect.TypeOf((*MockIConsumer)(nil).StartConsumer))
}
