// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-consumer/repositories (interfaces: INationalityRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-consumer/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockINationalityRepository is a mock of INationalityRepository interface.
type MockINationalityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockINationalityRepositoryMockRecorder
}

// MockINationalityRepositoryMockRecorder is the mock recorder for MockINationalityRepository.
type MockINationalityRepositoryMockRecorder struct {
	mock *MockINationalityRepository
}

// NewMockINationalityRepository creates a new mock instance.
func NewMockINationalityRepository(ctrl *gomock.Controller) *MockINationalityRepository {
	mock := &MockINationalityRepository{ctrl: ctrl}
	mock.recorder = &MockINationalityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockINationalityRepository) EXPECT() *MockINationalityRepositoryMockRecorder {
	return m.recorder
}

// GetOneByName mocks base method.
func (m *MockINationalityRepository) GetOneByName(arg0 context.Context, arg1 string) (models.Nationality, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByName", arg0, arg1)
	ret0, _ := ret[0].(models.Nationality)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByName indicates an expected call of GetOneByName.
func (mr *MockINationalityRepositoryMockRecorder) GetOneByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByName", reflect.TypeOf((*MockINationalityRepository)(nil).GetOneByName), arg0, arg1)
}
