// Code generated by MockGen. DO NOT EDIT.
// Source: escort-book-escort-consumer/repositories (interfaces: IProfileStatusCategoryRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "escort-book-escort-consumer/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIProfileStatusCategoryRepository is a mock of IProfileStatusCategoryRepository interface.
type MockIProfileStatusCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIProfileStatusCategoryRepositoryMockRecorder
}

// MockIProfileStatusCategoryRepositoryMockRecorder is the mock recorder for MockIProfileStatusCategoryRepository.
type MockIProfileStatusCategoryRepositoryMockRecorder struct {
	mock *MockIProfileStatusCategoryRepository
}

// NewMockIProfileStatusCategoryRepository creates a new mock instance.
func NewMockIProfileStatusCategoryRepository(ctrl *gomock.Controller) *MockIProfileStatusCategoryRepository {
	mock := &MockIProfileStatusCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockIProfileStatusCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProfileStatusCategoryRepository) EXPECT() *MockIProfileStatusCategoryRepositoryMockRecorder {
	return m.recorder
}

// GetOneByName mocks base method.
func (m *MockIProfileStatusCategoryRepository) GetOneByName(arg0 context.Context, arg1 string) (models.ProfileStatusCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByName", arg0, arg1)
	ret0, _ := ret[0].(models.ProfileStatusCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByName indicates an expected call of GetOneByName.
func (mr *MockIProfileStatusCategoryRepositoryMockRecorder) GetOneByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByName", reflect.TypeOf((*MockIProfileStatusCategoryRepository)(nil).GetOneByName), arg0, arg1)
}
